services:
  web:
    build:
      target: web-dev
    ports:
      - "3000:3000"
    environment:
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./packages/web/app:/app/packages/web/app
      - ./packages/web/public:/app/packages/web/public
      - ./packages/web/src:/app/packages/web/src
      - ./packages/shared/src:/app/packages/shared/src
      - ./packages/shared/dist:/app/packages/shared/dist
      - /app/packages/web/.next

  ws:
    ports:
      - "3001:3001"
